=== pidimo/bm/src/java/com/piramide/elwis/web/dashboard/component/configuration/reader/component-def.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % Boolean "(TRUE|FALSE)">
<!ENTITY % Action "(CLOSE|CONFIGURATION)">
<!ENTITY % Order "(ASC|DESC|NONE)">
<!ENTITY % DataType "(INTEGER|STRING|DATE|BOOLEAN)">
<!ENTITY % View "(TEXT|SELECT|CHECK|RANGE)">
<!ENTITY % defaultUiProcessors "(LIST|CUSTOM)">

<!ELEMENT components (dataProcessor,persistenceProcessor,conditionEvaluator?,converters?,component+)>

<!ELEMENT converters (converter+)>
<!ELEMENT converter (#PCDATA)>
<!ATTLIST converter
        name CDATA #REQUIRED
        class CDATA #REQUIRED>

<!ELEMENT dataProcessor (#PCDATA)>
<!ELEMENT persistenceProcessor (#PCDATA)>
<!ELEMENT filterPreProcessor (#PCDATA)>
<!ELEMENT conditionEvaluator (#PCDATA)>

<!ELEMENT uiProcessor (#PCDATA)>
<!ATTLIST uiProcessor
        type %defaultUiProcessors; #REQUIRED
        class CDATA #IMPLIED>

<!ELEMENT accessUrl (params)>
 <!ATTLIST accessUrl
        url CDATA #REQUIRED>

<!ELEMENT componentUrl (params)>
<!ATTLIST componentUrl
         url CDATA #REQUIRED>


<!ELEMENT params (param+)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
        name CDATA #REQUIRED
        value CDATA #IMPLIED
        columnId CDATA #IMPLIED>

<!ELEMENT component (columns?, filters?, windowOptions, configurations, params?)>
<!ATTLIST component
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        nameResource CDATA #REQUIRED
        functionality CDATA #IMPLIED
        permission CDATA #IMPLIED> 

<!ELEMENT columns (column)+>
<!ELEMENT column ((constant)*, (condition)*)>
<!ATTLIST column
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        resourceKey CDATA #IMPLIED
        order %Order; #IMPLIED
        default %Boolean; #IMPLIED
        accessColumn %Boolean; #IMPLIED
        patternKey CDATA #IMPLIED
        propertyName CDATA #IMPLIED
        converter CDATA #IMPLIED
        size CDATA #IMPLIED
        inverseOrder %Boolean; #IMPLIED>

<!ELEMENT constant (#PCDATA)>
<!ATTLIST constant
        value CDATA #REQUIRED
        resourceKey CDATA #REQUIRED>
<!ELEMENT condition (#PCDATA)>
<!ATTLIST condition
         type CDATA #REQUIRED
         operator CDATA #REQUIRED
         value CDATA #REQUIRED
         style CDATA #REQUIRED>

<!ELEMENT windowOptions (windowOption)+>
<!ELEMENT windowOption (#PCDATA)>
<!ATTLIST windowOption
        action CDATA #REQUIRED
        iconUrl CDATA #REQUIRED
        resourceKey CDATA #REQUIRED>

<!ELEMENT configurations ((uiProcessor,filterPreProcessor?,accessUrl?) | componentUrl)>


<!ELEMENT filters (filter*, staticFilter*, rowCounterFilter)>

<!ELEMENT filter (values)>
<!ATTLIST filter
        name CDATA #REQUIRED
        resourceKey CDATA #REQUIRED
        secondResourceKey CDATA #IMPLIED
        type %DataType; #IMPLIED
        view %View; #REQUIRED
        selectValue CDATA #IMPLIED
        selectId CDATA #IMPLIED>

<!ELEMENT staticFilter (#PCDATA)>
<!ATTLIST staticFilter
        name CDATA #REQUIRED
        multipleValue %Boolean; #IMPLIED>
<!ELEMENT rowCounterFilter (#PCDATA)>
<!ATTLIST rowCounterFilter
       name CDATA #REQUIRED
       resourceKey CDATA #REQUIRED
       value CDATA #REQUIRED>

<!ELEMENT values (query?,constantClass?,default?)>

<!ELEMENT query (params)>

<!ELEMENT constantClass (#PCDATA)>
<!ATTLIST constantClass
        className CDATA #REQUIRED
        methodName CDATA #REQUIRED>

<!ELEMENT default (#PCDATA)>
<!ATTLIST default
    value CDATA #REQUIRED>

=== pidimo/bm/src/web/WEB-INF/common/component-def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//dashboard/dashboard Config DTD //EN"
        "http://www.jatun.com/component-def.dtd">

<components>
    <dataProcessor>com.piramide.elwis.web.dashboard.conf.FantabulousProcessor</dataProcessor>
    <persistenceProcessor>com.piramide.elwis.web.dashboard.conf.PersistenceProcessor</persistenceProcessor>
    <conditionEvaluator>com.piramide.elwis.web.dashboard.conf.Evaluator</conditionEvaluator>
    <converters>
        <converter name="IntegerToDate" class="com.piramide.elwis.web.dashboard.conf.IntegerToDateDashboardConverter"/>
        <converter name="LongToDate" class="com.piramide.elwis.web.dashboard.conf.LongToDateDashboardConverter"/>
        <converter name="BirthdayAge" class="com.piramide.elwis.web.dashboard.conf.BirthdayAgeDashboardConverter"/>
        <converter name="BirthdayDateConverter"
                   class="com.piramide.elwis.web.dashboard.conf.BirthdayDateDashboardConverter"/>
        <converter name="DateTask" class="com.piramide.elwis.web.dashboard.conf.SchedulerTaskDashboardConverter"/>
        <converter name="TimeTaskConverter" class="com.piramide.elwis.web.dashboard.conf.TimeTaskDashboardConverter"/>
        <converter name="inboxSizeConverter" class="com.piramide.elwis.web.dashboard.conf.InboxSizeDashboardConverter"/>
    </converters>
    <component id="1" name="recent" nameResource="recentList" functionality="CONTACT" permission="VIEW">
        <columns>
            <column id="1" name="addressName" resourceKey="Contact.name" order="ASC" default="TRUE" size="35"/>
            <column id="2" name="sequence" accessColumn="TRUE"/>
            <column id="3" name="addressId" accessColumn="TRUE"/>
            <column id="4" name="addressType" accessColumn="TRUE"/>
            <column id="5" name="name1" accessColumn="TRUE"/>
            <column id="6" name="name2" accessColumn="TRUE"/>
            <column id="7" name="name3" accessColumn="TRUE"/>
            <column id="8" name="city" resourceKey="Contact.city" size="25"/>
            <column id="9" name="country" resourceKey="Contact.country" order="NONE" size="25"/>
            <column id="10" name="zip" resourceKey="Contact.zip" size="10"/>
        </columns>
        <filters>
            <rowCounterFilter name="numberOfElements" resourceKey="rowsPerPage" value="5"/>
        </filters>
        <windowOptions>
            <windowOption action="/Dashboard/Component/Configuration/read.do"
                          iconUrl="/layout/ui/img/configuration.gif"
                          resourceKey="Common.configuration"/>
            <windowOption action="/Dashboard/ComponentClose.do"
                          iconUrl="/layout/ui/img/close.gif"
                          resourceKey="Common.close"/>
        </windowOptions>
        <configurations>
            <uiProcessor type="LIST"/>
            <accessUrl url="/contacts/General/RecentAction.do">
                <params>
                    <param name="dto(addressId)" columnId="3"/>
                    <param name="dto(addressType)" columnId="4"/>
                    <param name="dto(name1)" columnId="5"/>
                    <param name="dto(name2)" columnId="6"/>
                    <param name="dto(name3)" columnId="7"/>
                    <param name="contactId" columnId="3"/>
                    <param name="module" value="contacts"/>
                    <param name="index" value="0"/>
                </params>
            </accessUrl>
        </configurations>
        <params>
            <param name="FantaListName" value="recentList"/>
            <param name="module" value="/contacts"/>
        </params>
    </component>
    <component id="2" name="task" nameResource="scheduler.MyTaskList" functionality="TASK" permission="VIEW">
        <columns>
            <column id="1" name="title" resourceKey="Task.taskName" default="TRUE" order="NONE" size="29"/>
            <column id="2" name="startDate" resourceKey="Task.shortStartDate" default="TRUE" converter="DateTask"
                    order="NONE" size="15"/>
            <column id="3" name="expireDate" resourceKey="Task.shortExpireDate" default="TRUE" converter="DateTask"
                    order="DESC" size="15"/>
            <column id="4" name="status" resourceKey="Task.status" default="TRUE" size="19">
                <constant value="1" resourceKey="Task.InProgress"/>
                <constant value="2" resourceKey="Task.notInit"/>
                <constant value="3" resourceKey="Scheduler.Task.Concluded"/>
                <constant value="4" resourceKey="Task.Deferred"/>
                <constant value="5" resourceKey="Task.ToCheck"/>
            </column>
            <column id="5" name="taskId" accessColumn="TRUE"/>
            <column id="6" name="title" accessColumn="TRUE"/>
            <column id="7" name="startDateTime" accessColumn="TRUE"/>
            <column id="8" name="expireDateTime" accessColumn="TRUE"/>
            <column id="9" name="priority" resourceKey="Task.priority" size="15"/>
            <column id="10" name="expireDate" accessColumn="TRUE">
                <condition type="date" operator="equal" value="now" style="nowDate"/>
            </column>
            <column id="11" name="createDateTime" accessColumn="TRUE" order="DESC"/>
            <column id="12" name="startTime" resourceKey="Task.startTime" size="9" converter="TimeTaskConverter"/>
            <column id="13" name="expireTime" resourceKey="Task.expireTime" size="9" converter="TimeTaskConverter"/>
        </columns>
        <filters>
            <filter name="priorityOfTask" resourceKey="Task.priority" view="SELECT" selectId="id"
                    selectValue="name">
                <values>
                    <query>
                        <params>
                            <param name="FantaListName" value="selectPriorityList"/>
                            <param name="module" value="/catalogs"/>
                            <param name="companyId" value="${sessionScope.user.valueMap['companyId']}"/>
                            <param name="type" value="SCHEDULER"/>
                        </params>
                    </query>
                </values>
            </filter>
            <filter name="statusBk" resourceKey="Task.status" view="SELECT">
                <values>
                    <constantClass className="com.piramide.elwis.web.common.util.JSPHelper"
                                   methodName="getPriorityStatusListForTaskComponent"/>
                </values>
            </filter>
            <rowCounterFilter name="numberOfElements" resourceKey="rowsPerPage" value="5"/>
        </filters>
        <windowOptions>
            <windowOption action="/Dashboard/Component/Configuration/read.do"
                          iconUrl="/layout/ui/img/configuration.gif"
                          resourceKey="Common.configuration"/>
            <windowOption action="/Dashboard/ComponentClose.do"
                          iconUrl="/layout/ui/img/close.gif"
                          resourceKey="Common.close"/>
        </windowOptions>
        <configurations>
            <uiProcessor type="LIST"/>
            <accessUrl url="/Dashboard/Task/ActionSelector.do">
                <params>
                    <param name="taskId" columnId="5"/>
                    <param name="dto(title)" value="6"/>
                    <param name="dto(recordUserId)" value="${sessionScope.user.valueMap['userId']}"/>
                    <param name="module" value="scheduler"/>
                </params>
            </accessUrl>
        </configurations>
        <params>
            <param name="FantaListName" value="dashboardTaskList"/>
            <param name="module" value="/scheduler"/>
        </params>
    </component>
    <component id="3" name="salesProcess" nameResource="salesProcessOpen.List" functionality="SALESPROCESS"
               permission="VIEW">
        <columns>
            <column id="1" name="processName" resourceKey="SalesProcess.name" default="TRUE" order="NONE" size="23"/>
            <column id="2" name="addressName" resourceKey="SalesProcess.contact" default="TRUE" order="NONE" size="23"/>
            <column id="3" name="endDate" resourceKey="Common.expiration" default="TRUE" converter="IntegerToDate"
                    order="DESC" size="15"/>
            <column id="4" name="processId" accessColumn="TRUE"/>
            <column id="5" name="addressId" accessColumn="TRUE"/>
            <column id="6" name="processName" accessColumn="TRUE"/>
            <column id="7" name="priorityName" resourceKey="SalesProcess.priority" size="10"/>
            <column id="8" name="probability" resourceKey="SalesProcess.probability" patternKey="dashboard.percent"
                    size="10"/>
            <column id="9" name="value" resourceKey="SalesProcess.value" patternKey="numberFormat.2DecimalPlaces"
                    size="14"/>
        </columns>
        <filters>
            <rowCounterFilter name="numberOfElements" resourceKey="rowsPerPage" value="5"/>
        </filters>
        <windowOptions>
            <windowOption action="/Dashboard/Component/Configuration/read.do"
                          iconUrl="/layout/ui/img/configuration.gif"
                          resourceKey="Common.configuration"/>
            <windowOption action="/Dashboard/ComponentClose.do"
                          iconUrl="/layout/ui/img/close.gif"
                          resourceKey="Common.close"/>
        </windowOptions>
        <configurations>
            <uiProcessor type="LIST"/>
            <accessUrl url="/sales/SalesProcess/Forward/Update.do">
                <params>
                    <param name="processId" columnId="4"/>
                    <param name="dto(processId)" columnId="4"/>
                    <param name="addressId" columnId="5"/>
                    <param name="dto(processName)" columnId="6"/>
                    <param name="index" value="0"/>
