=== pidimo/bm/data/fantabulous/dtd/fantabulous-config.dtd
<!ELEMENT lists (list+)>
  <!ELEMENT list  ( tables+, relationShips*, conditions, configuration ) >
  <!ATTLIST list listName CDATA #REQUIRED>
<!-- Add for status-->
  <!ATTLIST list persistence CDATA "true">
  <!ATTLIST list executeFirstTime CDATA "true">
  <!ATTLIST list alwaysRead CDATA "true">
<!-- to here -->
  <!ATTLIST list distinct CDATA "true">
  <!ATTLIST list extends CDATA>
  <!ELEMENT tables (table+)>
  <!ELEMENT relationShips (relationShip*)>
  <!ATTLIST  table tableName CDATA >
  <!ATTLIST  table alias CDATA #REQUIRED>
  <!ELEMENT  table  ( fields+ )>
  <!ELEMENT  fields (field+)>
  <!ELEMENT  field >
  <!ATTLIST  field fieldName CDATA #REQUIRED>
  <!ATTLIST  field  fieldAlias CDATA #REQUIRED>
  <!ATTLIST  field  key CDATA "true">
  <!ELEMENT  relationShip  (leftJoin?, outerJoin? fK, pK, conditions?)>
  <!ELEMENT  leftJoin  (#PCDATA)>
  <!ELEMENT  outerJoin  (#PCDATA)>
  <!ELEMENT  fK (#PCDATA)>
  <!ELEMENT  pK (#PCDATA)>
  <!ELEMENT  referenceField (#PCDATA)>

  <!--<!ELEMENT Configuration (List+)>-->
  <!ELEMENT  configuration  (  columns , defaultOrder?)>
  <!ELEMENT  columns (  column+ )>
  <!ELEMENT  column  ( config, function? )>
  <!ATTLIST  column  columnName CDATA #REQUIRED>
  <!ELEMENT  config  (  fieldsConfig | formats , fieldsOrder )>
  <!ELEMENT  fieldsConfig  ( referenceField+  )>
  <!ATTLIST  fieldsConfig separator CDATA>
  <!ELEMENT  formats  (  format+ )>
  <!ELEMENT  format ( conditions, fieldFormat )>
  <!ELEMENT  fieldFormat  ( referenceField  separator fieldFormat
                          | referenceField separator>
                          | referenceField)>
  <!ELEMENT  separator  ( #PCDATA )>
  <!ELEMENT  defaultOrder  ( columnOrder )>
  <!ATTLIST  defaultOrder  orderBy ( ASC | DESC) #REQUIRED>
  <!ELEMENT  columnOrder>
  <!ATTLIST  columnOrder  columnName CDATA #REQUIRED>
 <!ELEMENT  fieldsOrder  ( referenceField+ )>
  <!ELEMENT  function (  AVG
   |  COUNT
   |  SUM
   |  MAX
   |  MIN )>
  <!ELEMENT   where   (  conditions
     |  conditions groupBy
     |  between ) >
  <!ELEMENT  groupBy   (   referenceField+  having  )>
  <!ELEMENT  between  (  value value  )>
  <!ELEMENT  having  (  conditions  )>
  <!ELEMENT  operator  ( EQUAL  | DISTINCT | EQUAL_GREATER | EQUAL_LESS | LESS | GREATER )>
  <!ELEMENT  conditions  ( condition   |   condition   conector   conditions )>
  <!ATTLIST  condition fieldReference CDATA #REQUIRED>
  <!ATTLIST  condition operator (LIKE | LIKE2 | EQUAL | GREATER | LESS |GREATER_EQUAL | LESS_EQUAL | DISTINCT | ANDBIT) #REQUIRED>
  <!ATTLIST  condition type ( constant | parameter | field) CDATA #REQUIRED>
  <!ATTLIST  condition value  CDATA>
  <!ELEMENT  condition>
  <!ELEMENT  conector     (  AND    |   OR  )>
  <!ELEMENT  parameter >
  <!ELEMENT  constant >

=== pidimo/bm/src/web/WEB-INF/scheduler/fantabulous.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE fantabulous-config PUBLIC
  "-//Alfacentauro//Fantabulous//Fantabulous DTD 1.0//EN"
  "fantabulous-config.dtd">-->

<lists>
    <list listName="taskList" persistence="true" distinct="true">
        <tables>
            <table tableName="task" alias="task">
                <fields>
                    <field fieldName="taskid" fieldAlias="taskId" key="true" type="integer"/>
                    <field fieldName="title" fieldAlias="title"/>
                    <field fieldName="expiredatetime" fieldAlias="expireDate" type="integer"/>
                    <field fieldName="startdatetime" fieldAlias="startDate" type="integer"/>
                    <field fieldName="status" fieldAlias="status" type="integer"/>
                    <field fieldName="priorityid" fieldAlias="taskPriorityId" type="integer"/>
                    <field fieldName="addressid" fieldAlias="contactId" type="integer"/>
                    <field fieldName="companyid" fieldAlias="companyId" type="integer"/>
                    <field fieldName="userid" fieldAlias="ownerId" type="integer"/>
                    <field fieldName="processid" fieldAlias="processId" type="integer"/>
                </fields>
            </table>
            <table tableName="elwisuser" alias="user">
                <fields>
                    <field fieldName="userid" fieldAlias="elwisUserId" key="true" type="integer"/>
                    <field fieldName="addressid" fieldAlias="addressId" type="integer"/>
                </fields>
            </table>
            <table tableName="address" alias="addressName">
                <fields>
                    <field fieldName="addressid" fieldAlias="addressNameId" key="true" type="integer"/>
                    <field fieldName="name1" fieldAlias="addressName1"/>
                    <field fieldName="name2" fieldAlias="addressName2"/>
                </fields>
            </table>
            <table tableName="address" alias="contactName">
                <fields>
                    <field fieldName="addressid" fieldAlias="contactNameId" key="true" type="integer"/>
                    <field fieldName="name1" fieldAlias="contactName1"/>
                    <field fieldName="name2" fieldAlias="contactName2"/>
                    <field fieldName="name3" fieldAlias="contactName3"/>
                    <field fieldName="addresstype" fieldAlias="addressType"/>
                </fields>
            </table>
            <table tableName="scheduleduser" alias="scheduledUser">
                <fields>
                    <field fieldName="scheduleduserid" fieldAlias="scheduledUserId" key="true" type="integer"/>
                    <field fieldName="taskid" fieldAlias="userTaskId" type="integer"/>
                    <field fieldName="userid" fieldAlias="userId" type="integer"/>
                </fields>
            </table>
            <table tableName="usertask" alias="userTask">
                <fields>
                    <field fieldName="scheduleduserid" fieldAlias="scheduledUserId_" key="true" type="integer"/>
                    <field fieldName="statusid" fieldAlias="participantStatus" type="integer"/>
                </fields>
            </table>
            <table tableName="priority" alias="priority">
                <fields>
                    <field fieldName="priorityid" fieldAlias="priorityId" key="true" type="integer"/>
                    <field fieldName="priorityname" fieldAlias="priorityName"/>
                    <field fieldName="sequence" fieldAlias="sequence" type="integer"/>
                </fields>
            </table>

        </tables>
        <relationShips>
            <relationShip>
                <leftJoin/>
                <pK>priorityId</pK>
                <fK>taskPriorityId</fK>
            </relationShip>
            <relationShip>
                <pK>userTaskId</pK>
                <fK>taskId</fK>
            </relationShip>
            <relationShip>
                <pK>scheduledUserId_</pK>
                <fK>scheduledUserId</fK>
            </relationShip>
            <relationShip>
                <pK>elwisUserId</pK>
                <fK>ownerId</fK>
            </relationShip>
            <relationShip>
                <pK>addressNameId</pK>
                <fK>addressId</fK>
            </relationShip>
            <relationShip>
                <leftJoin/>
                <pK>contactNameId</pK>
                <fK>contactId</fK>
            </relationShip>
        </relationShips>
        <conditions>
            <condition fieldReference="companyId" operator="EQUAL" type="parameter"/>
            <conector>And</conector>
            <condition fieldReference="processId" operator="EQUAL" type="parameter"/>
            <conector>And</conector>
            <condition fieldReference="contactId" operator="EQUAL" type="parameter" parameterName="addressId"/>
            <conector>And</conector>
            <conditions>
                <condition fieldReference="participantStatus" operator="DISTINCT" type="constant" value="3"/>
                <conector>And</conector>
                <condition fieldReference="userId" operator="EQUAL" type="parameter" parameterName="scheduledUserId"/>
                <conector>And</conector>
                <condition fieldReference="userId" operator="EQUAL" type="parameter" parameterName="userId"/>
                <conector>And</conector>
                <condition fieldReference="ownerId" operator="DISTINCT" type="parameter" parameterName="userId"/>
            </conditions>
            <conector>Or</conector>
            <conditions>
                <condition fieldReference="ownerId" operator="EQUAL" type="parameter" parameterName="userId"/>
                <conector>And</conector>
                <condition fieldReference="userId" operator="EQUAL" type="parameter" parameterName="scheduledUserId"/>
                <conector>And</conector>
                <condition fieldReference="userId" operator="DISTINCT" type="parameter" parameterName="userId"/>
                <conector>And</conector>
                <condition fieldReference="status" operator="DISTINCT" type="constant" value="3"/>
            </conditions>
            <conector>Or</conector>
            <conditions>
                <condition fieldReference="ownerId" operator="EQUAL" type="parameter" parameterName="userId"/>
                <conector>And</conector>
                <condition fieldReference="userId" operator="EQUAL" type="parameter" parameterName="userId"/>
                <conector>And</conector>
                <condition fieldReference="status" operator="DISTINCT" type="constant" value="3"/>
                <conector>And</conector>
                <condition fieldReference="title" operator="LIKE" type="parameter"/>
                <conector>And</conector>
                <condition fieldReference="title" operator="LIKE2" type="parameter" parameterName="titleAlphabet"/>
            </conditions>
        </conditions>
        <configuration>
            <columns>
                <column columnName="taskId">
                    <config>
                        <fieldsConfig>
                            <referenceField>taskId</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="title">
                    <config>
                        <fieldsConfig>
                            <referenceField>title</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="startDate">
                    <config>
                        <fieldsConfig>
                            <referenceField>startDate</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="expireDate">
                    <config>
                        <fieldsConfig>
                            <referenceField>expireDate</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="priorityName">
                    <config>
                        <fieldsConfig>
                            <referenceField>priorityName</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="status">
                    <config>
                        <fieldsConfig>
                            <referenceField>status</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="ownerId">
                    <config>
                        <fieldsConfig>
                            <referenceField>ownerId</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="sequence">
                    <config>
                        <fieldsConfig>
                            <referenceField>sequence</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="ownerName">
                    <config>
                        <fieldsConfig separator=", ">
                            <referenceField>addressName1</referenceField>
                            <referenceField>addressName2</referenceField>
                        </fieldsConfig>
                    </config>
                </column>
                <column columnName="contactName">
                    <config>
                        <formats>
                            <format>
                                <conditions>
